### ISSUE TITLE
Connectivity check error

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#1127]
In GitLab by @eferre1 on Sep 7, 2023, 15:59

Hello @dbeltrankyl and @kinow,

### Autosubmit Version

autosubmit/4.0.88-foss-2021b-Python-3.9.6 from the Autosubmit Hub (`bsceshub02.bsc.es`)

### Expid affected

- t0d7

### Which task has issues? Where is the log(If applicable)

`autosubmit run` - The log of the last test are:

- `/esarchive/autosubmit/t0d7/tmp/ASLOGS/20230907_154255_run_err.log`
- `/esarchive/autosubmit/t0d7/tmp/ASLOGS/20230907_154255_run.log`

### Summary

The initial connection to the platforms of the experiment is failing, and it complains that it doesn't have passwordless connection. The platform is an `ecaccess` platform, which means that the submission of jobs is not done via `ssh`, so the connection check should try to test that way.

### Steps to reproduce

Create an experiment in autosubmit 4 to run in ECMWF-HPC2020 through ecaccess, and try to run it (`autosubmit run`).

### What is the current bug behavior?

Connection error during the platforms check.

### What is the expected correct behavior?

Check the connection using ecaccess too.

### Relevant logs and/or screenshots

Below I add the run terminal output where it complains about the connection.

```shell
Scripts OK
Autosubmit is running with v4.0.88
Checking the connection to all platforms in use
NotAfter: Thu Apr 20 15:47:08 UTC 2023
Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 2045, in run_experiment
    job_list, submitter , exp_history, host , as_conf, platforms_to_test, packages_persistence, _ = Autosubmit.prepare_run(expid, notransitive,start_time, start_after, run_only_members)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 1985, in prepare_run
    Autosubmit.restore_platforms(platforms_to_test)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 2331, in restore_platforms
    raise AutosubmitCritical("Issues while checking the connectivity of platforms.", 7010, issues + "\n" + ssh_config_issues)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 658, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.start_time,args.start_after, args.run_only_members, args.profile)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 2048, in run_experiment
    raise AutosubmitCritical(e.message, 7014, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: 
[ECMWF-HPC2020] has configuration issues.
 Check that the connection is passwd-less.(ssh c3ef@hpc-login-spesiccf)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/ec/res4/scratch/spesiccf/c3ef}

 [CRITICAL] Issues while checking the connectivity of platforms. HINT: check the CUSTOM_DIRECTIVE syntax in your jobs configuration files. [eCode=7014]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

### Any other relevant information

As always, it might be another error hidden somewhere before the real reported error, but since I'm creating a new workflow from scratch and don't have a lot of complex things involved for now, I'm not seeing if it is another thing.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Sep 12, 2023, 08:38

I forgot to mention it clearly, just a comment on the autosubmit version, I'm running on the Autosubmit HUB, not the usual machines. With AS-3.15 we know it works since it is being used in auto-ecearth3, but here for auto-ecearth4 we are already using AS-4 and it is when the issue appears.

**Comment by kinow** [comment]
In GitLab by @eferre1 on Sep 12, 2023, 09:16

Nevermind, just doing some tests again I noticed the `HINT` about the `CUSTOM_DIRECTIVES`, and found out that I had not defined them properly, now it is working. Closing the issue.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 12, 2023, 09:27

Ah, what was the message? maybe it was missleading

**Comment by kinow** [comment]
In GitLab by @eferre1 on Sep 12, 2023, 09:33

Ok, sorry for the confusion, it seems that it is still not working. I had issues with both the `report -all` and the `run` commands, so after fixing the `CUSTOM_DIRECTIVES` I ran first a `report -all` and it worked, so I thought that it was solved, but it turns out that it still fails when trying to do the `run`.


This is my current platform settings (user and project come from another file):
```yml
  ECMWF-HPC2020:
    TYPE: ecaccess
    VERSION: slurm
    HOST: hpc-login
    QUEUE: nf
    EC_QUEUE: hpc
    BUDGET:
    SCRATCH_DIR: /ec/res4/scratch
    ADD_PROJECT_TO_HOST: false
    MAX_WALLCLOCK: 48:00
    CUSTOM_DIRECTIVES: '#SBATCH --hint=nomultithread'


  ECMWF-HPC2020:
    PROJECT: spesiccf
    USER: c3ef
```
The `report -all` now works:
```shell
[eferre1@ bsceshub02 as4]$ autosubmit report -all t0d7
Autosubmit is running with 4.0.88
Creating jobs...
Loading JobList
Adding dependencies...
Removing redundant dependencies...
Using existing valid structure.
Looking for edgeless jobs...
Gathering all parameters (all keys are on upper_case)
A list of all parameters has been written on /esarchive/autosubmit/t0d7/tmp/t0d7_parameter_list_20230912-093118.txt
```

But the `run` still doesn't, and this is the message of it:
```shell
Scripts OK
Autosubmit is running with v4.0.88
Checking the connection to all platforms in use
NotAfter: Thu Apr 20 15:47:08 UTC 2023
Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 2045, in run_experiment
    job_list, submitter , exp_history, host , as_conf, platforms_to_test, packages_persistence, _ = Autosubmit.prepare_run(expid, notransitive,start_time, start_after, run_only_members)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 1985, in prepare_run
    Autosubmit.restore_platforms(platforms_to_test)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 2331, in restore_platforms
    raise AutosubmitCritical("Issues while checking the connectivity of platforms.", 7010, issues + "\n" + ssh_config_issues)
log.log.AutosubmitCritical:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/EGG-INFO/scripts/autosubmit", line 37, in main
    Autosubmit.parse_args()
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 658, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.start_time,args.start_after, args.run_only_members, args.profile)
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/autosubmit/4.0.88-foss-2021b-Python-3.9.6/lib/python3.9/site-packages/autosubmit-4.0.88-py3.9.egg/autosubmit/autosubmit.py", line 2048, in run_experiment
    raise AutosubmitCritical(e.message, 7014, e.trace)
log.log.AutosubmitCritical:  
[ERROR] Trace: 
[ECMWF-HPC2020] has configuration issues.
 Check that the connection is passwd-less.(ssh c3ef@hpc-login)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/ec/res4/scratch/spesiccf/c3ef}

 [CRITICAL] Issues while checking the connectivity of platforms. HINT: check the CUSTOM_DIRECTIVE syntax in your jobs configuration files. [eCode=7014]
More info at https://autosubmit.readthedocs.io/en/master/troubleshooting/error-codes.html
```

**Comment by kinow** [comment]
In GitLab by @eferre1 on Sep 12, 2023, 13:06

mentioned in issue auto-ecearth4#1

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Sep 12, 2023, 15:50

Some commits were missing from 3.15. Also, I had to do some adaptations to make it work with this version. 

It should've been fixed in v4.0.90. Available in the hubs

**Comment by kinow** [comment]
In GitLab by @eferre1 on Sep 14, 2023, 14:20

Hi, with the changes for the v4.0.90 it works. It also happened that since I was using `ecaccess` as the connection method and it was reporting an issue of the platform not being `ssh passwordless` accessible, I didn't notice that I hadn't run the `ecaccess-certificate-create` command, so that was mainly the real issue (the missing commits might have come in later when trying to submit the job to the `ecs` or `hpc` login with the `ecs_queue` parameter).

So now, as said, it is working, but it would be nice to modify the message so it mentions something regarding the certificate if the connection check fails and the platform uses `ecaccess` instead of a direct `ssh` connection. So, instead of:

```
[ECMWF-HPC2020] has configuration issues.
 Check that the connection is passwd-less.(ssh c3ef@hpc-login)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/ec/res4/scratch/spesiccf/c3ef}
```

Something like this would be better (if possible):

```
[ECMWF-HPC2020] has configuration issues.
 The connection is ecaccess based, check that the certificate is correct.(ecaccess-certificate-list)
 Check the parameters that build the root_path are correct:{scratch_dir/project/user} = {/ec/res4/scratch/spesiccf/c3ef}
```

**Comment by kinow** [comment]
In GitLab by @etiennesky on Oct 4, 2023, 20:17

I agree the error message should be changed, it caused some confusion from my side when I was having issues reported in #1139

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 16, 2024, 12:06

unassigned @dbeltrankyl

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 16, 2024, 12:08

Fyi @isimo00, if you want to do it otherwise, I'll do it 

I am bumping this issue as was commented on there
https://earth.bsc.es/gitlab/es/auto-ecearth3/-/issues/2049#note_313069 

TODO: 

* [ ] Check the error message in AS 4.1.11+ 
* [ ] Change the connection check in all platforms( ecmwf, lsf, slurm , local , ps ) so it creates the folder if it doesn't exists

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 16, 2024, 12:09

mentioned in issue auto-ecearth3#2049

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Oct 16, 2024, 12:10

Also it is related to this one https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1429 ( the part of the log message)

**Comment by kinow** [comment]
In GitLab by @isimo00 on Oct 16, 2024, 14:30

Thanks, I'll give it a go and try to take care of it!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Nov 5, 2024, 12:41

Hello @isimo00 

What is the status of this issue? Should I move it to 4.1.12? Can you reference the associated merge? thanks!

**Comment by kinow** [comment]
In GitLab by @isimo00 on Nov 5, 2024, 12:51

Hi, I still haven't worked on it, so you can move it to 4.1.12, yes. Thanks!

**Comment by VindeeR** [comment]
@dbeltrankyl do you think your fixes at #2939 will be fixing this issue? Or maybe this was already previously fixed?

**Comment by dbeltrankyl** [comment]
No, this is a different issue, I believe. 

What I fixed was the submission.

 What this is complaining about is the first message when Autosubmit checks that everything is okay with all the platforms that the experiment is using before starting the autosubmit run or any other "online" command

**Comment by dbeltrankyl** [comment]
Hello @rajeshsuraj 

I see you assigned yourself, but there is no associated PR. Could you link it and report the status of this issue? 

I'll move it to 4.2.1 for now

Thanks!

**Comment by rajeshsuraj** [comment]
Hi @dbeltrankyl  , i was investigating this issue and found that the bug is still producible  on 4.1.17. but not checked on master current (4.2.0)

the issue is that EcPlatform.connect()` only logs a warning when `ecaccess-gateway-connected` says no, so `test_connection` returns `None` and `restore_platforms` treats it as ok so patching that should fix this issue as well.

Thanks !

**Comment by manuel-g-castro** [comment]
@f-macchia is there any ecmwf testbench cluster that we can use to test if this changes are working?
